/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_kutec_hellojni_JniTest */

#ifndef _Included_cn_kutec_hellojni_JniTest
#define _Included_cn_kutec_hellojni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_kutec_hellojni_JniTest
 * Method:    getStringFromNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_kutec_hellojni_JniTest_getStringFromNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
